#!/usr/bin/env python3
"""
Build Oracle - Phase 1 of the Dead Feature Detector.

Reads a compile_commands.json (generated by CMake with
CMAKE_EXPORT_COMPILE_COMMANDS=ON) and extracts every preprocessor
definition (-D flag) actually passed to the compiler in any
translation unit.

The output is a structured JSON document of the form:

{
  "defines": {
    "DEBUG":      { "values": ["1"],  "files": ["src/a.cpp"] },
    "FEATURE_X":  { "values": [""],   "files": ["src/b.cpp"] },
    "VERSION":    { "values": ["2"],  "files": ["src/a.cpp", "src/b.cpp"] }
  },
  "files_analyzed": 2,
  "source": "<path to compile_commands.json>"
}

A macro defined without a value (e.g. -DFEATURE_X) is recorded as the
empty string "" -- the LLVM pass treats that as the canonical "set but
unvalued" form.
"""

import argparse
import json
import os
import shlex
import sys
from collections import defaultdict


def iter_compiler_args(entry):
    """
    A compile_commands.json entry may use either an "arguments" list
    or a single "command" string. Yield the individual tokens.
    """
    if "arguments" in entry:
        for tok in entry["arguments"]:
            yield tok
    elif "command" in entry:
        for tok in shlex.split(entry["command"]):
            yield tok
    else:
        return


def parse_defines(tokens):
    """
    Walk a token stream and yield (name, value) pairs for every -D flag.

    Handles:  -DNAME            -> ("NAME", "")
              -DNAME=VAL        -> ("NAME", "VAL")
              -D NAME           -> ("NAME", "")
              -D NAME=VAL       -> ("NAME", "VAL")
    """
    tokens = list(tokens)
    i = 0
    while i < len(tokens):
        tok = tokens[i]
        payload = None
        if tok.startswith("-D") and len(tok) > 2:
            payload = tok[2:]
        elif tok == "-D" and i + 1 < len(tokens):
            payload = tokens[i + 1]
            i += 1
        if payload is not None:
            if "=" in payload:
                name, value = payload.split("=", 1)
            else:
                name, value = payload, ""
            yield name, value
        i += 1


def build_oracle(compile_commands_path):
    with open(compile_commands_path, "r") as f:
        db = json.load(f)

    # name -> { value -> set(files) }
    table = defaultdict(lambda: defaultdict(set))
    files_seen = set()

    for entry in db:
        src = entry.get("file", "<unknown>")
        files_seen.add(src)
        for name, value in parse_defines(iter_compiler_args(entry)):
            table[name][value].add(src)

    defines = {}
    for name in sorted(table):
        values = sorted(table[name].keys())
        files = sorted({f for vs in table[name].values() for f in vs})
        defines[name] = {"values": values, "files": files}

    return {
        "defines": defines,
        "files_analyzed": len(files_seen),
        "source": os.path.abspath(compile_commands_path),
    }


def main():
    ap = argparse.ArgumentParser(description="Extract -D flags from compile_commands.json.")
    ap.add_argument("compile_commands", help="Path to compile_commands.json")
    ap.add_argument("-o", "--output", default="build_oracle.json",
                    help="Output JSON path (default: build_oracle.json)")
    args = ap.parse_args()

    if not os.path.isfile(args.compile_commands):
        print(f"error: {args.compile_commands} not found", file=sys.stderr)
        sys.exit(1)

    oracle = build_oracle(args.compile_commands)
    with open(args.output, "w") as f:
        json.dump(oracle, f, indent=2)

    print(f"Wrote {args.output}: "
          f"{len(oracle['defines'])} unique macros across "
          f"{oracle['files_analyzed']} translation unit(s).")


if __name__ == "__main__":
    main()
